version: '3.4'

services:
  init-certs:
    image: busybox
    volumes:
      - ./certs:/certs
    command: >
      sh -c "mkdir -p /certs/issued && chmod -R 777 /certs && echo 'Init tasks completed.'"

  fenrir:
    image: fenrir
    depends_on:
      - init-certs
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - 5003:5000
      - 5678:5678
    environment:
      - FLASK_APP=app.py
